// <auto-generated />
using System;
using IAmHakim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IAmHakim.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531122500_AddBookingLanguage")]
    partial class AddBookingLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("IAmHakim.Api.Models.Booking", b =>
                {
                    b.Property<string>("Id").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<string>("CalendarEventId").HasColumnType("longtext");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("DecidedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("DecisionToken").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<DateTimeOffset?>("ExpiresAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("EndUtc").HasColumnType("datetime(6)");
                    b.Property<int>("Kind").HasColumnType("int");
                    b.Property<string>("Language").IsRequired().HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<string>("ManageToken").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("Message").HasMaxLength(2000).HasColumnType("varchar(2000)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(16).HasColumnType("varchar(16)");
                    b.Property<DateTimeOffset?>("RequestedEndUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("RequestedStartUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("StartUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(24).HasColumnType("varchar(24)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex("DecisionToken").IsUnique();
                    b.HasIndex("ManageToken").IsUnique();
                    b.HasIndex("RequestedStartUtc");
                    b.HasIndex("StartUtc");
                    b.HasIndex("Email", "Status", "CreatedAtUtc");
                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
