// <auto-generated />
using System;
using IAmHakim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Pomelo.EntityFrameworkCore.MySql.Metadata;

#nullable disable

namespace IAmHakim.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531183000_AddBookingMeetingLocation")]
    partial class AddBookingMeetingLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);
            modelBuilder.HasAnnotation("MySql:CharSet", "utf8mb4");

            modelBuilder.Entity("IAmHakim.Api.Models.Booking", b =>
                {
                    b.Property<string>("Id").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<string>("CalendarEventId").HasColumnType("longtext");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("DecidedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("DecisionToken").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<DateTimeOffset?>("ExpiresAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("IpHash").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<DateTimeOffset>("EndUtc").HasColumnType("datetime(6)");
                    b.Property<int>("Kind").HasColumnType("int");
                    b.Property<string>("Language").IsRequired().HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<string>("ManageToken").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("Message").HasMaxLength(2000).HasColumnType("varchar(2000)");
                    b.Property<string>("MeetingLocation").HasMaxLength(300).HasColumnType("varchar(300)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("varchar(120)");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(16).HasColumnType("varchar(16)");
                    b.Property<DateTimeOffset?>("RequestedEndUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("RequestedStartUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("StartUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(24).HasColumnType("varchar(24)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.HasIndex("DecisionToken").IsUnique();
                    b.HasIndex("ManageToken").IsUnique();
                    b.HasIndex("RequestedStartUtc");
                    b.HasIndex("StartUtc");
                    b.HasIndex("Email", "Status", "CreatedAtUtc");
                    b.HasIndex("IpHash", "Status", "CreatedAtUtc");
                    b.ToTable("Bookings");
                });



            modelBuilder.Entity("IAmHakim.Api.Models.EmailVerification", b =>
                {
                    b.Property<string>("Id").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<int>("Attempts").HasColumnType("int");
                    b.Property<string>("CodeHash").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<DateTimeOffset?>("ConsumedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<DateTimeOffset>("ExpiresAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("IpHash").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<DateTimeOffset?>("VerifiedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("VerificationToken").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("Email");
                    b.HasIndex("ExpiresAtUtc");
                    b.HasIndex("IpHash", "CreatedAtUtc");
                    b.HasIndex("VerificationToken").IsUnique();
                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("IAmHakim.Api.Models.SiteEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Kind").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<string>("Label").IsRequired().HasMaxLength(220).HasColumnType("varchar(220)");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAtUtc");
                    b.ToTable("SiteEvents");
                });

            modelBuilder.Entity("IAmHakim.Api.Models.SiteStat", b =>
                {
                    b.Property<int>("Id").HasColumnType("int");
                    b.Property<long>("AlgoRuns").HasColumnType("bigint");
                    b.Property<long>("Clicks").HasColumnType("bigint");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("LastUpAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("LastVisitAtUtc").HasColumnType("datetime(6)");
                    b.Property<long>("TotalVisits").HasColumnType("bigint");
                    b.Property<long>("UpClicks").HasColumnType("bigint");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id");
                    b.ToTable("SiteStats");
                });
#pragma warning restore 612, 618
        }
    }
}
